language: csharp

os:
 - linux
 - osx

dist: bionic
osx_image: xcode9.1

mono: none
dotnet: 2.2.402

env:
  - TEST_SUITE="without-cultures"
  - TEST_SUITE="cultures"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 2048; fi
install:
  - dotnet tool install -g dotnet-format --version 4.0.40103 --add-source https://dotnet.myget.org/F/format/api/v3/index.json
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet-format --version
before_script:
  - echo "Checking format..." 
  - dotnet format --check --dry-run -w . -v diagnostic # check C# formatting for neo.sln
  - cd neo.UnitTests
script: |
  if [[ "$TEST_SUITE" == "cultures" ]]; then
      dotnet test -v m --filter FullyQualifiedName=Neo.UnitTests.UT_Culture.All_Tests_Cultures
  else
      if [[ "$TEST_SUITE" == "without-cultures" && "$TRAVIS_OS_NAME" == "linux" ]]; then
        # Test & Calculate coverage
        find * -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
        dotnet test -v m --filter FullyQualifiedName!=Neo.UnitTests.UT_Culture.All_Tests_Cultures /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      else
        # Only test
        dotnet test -v m --filter FullyQualifiedName!=Neo.UnitTests.UT_Culture.All_Tests_Cultures
      fi
  fi
after_success: |
  if [[ "$TEST_SUITE" == "without-cultures" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    # Send coverage
    echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    bash <(curl -s https://codecov.io/bash) -v
  fi


